name: CI Pipeline
run-name: Run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [25.x]
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: npm install
      - name: Production build
        run: npm run build:prod
      - name: Lint typescript
        id: lint_ts
        run: npm run lint:ts
      - name: Lint css
        id: lint_css
        run: npm run lint:scss
      - name: Unit tests
        id: unit_tests
        run: npm run test:unit
      - name: Build storybook
        run: npm run storybook:build
      - name: Screenshot tests
        id: screenshot_tests
        run: |
            npm run test:ui:ci
      - name: Upload build debug data
        if: failure() &&
           (steps.lint_ts.outcome == 'failure' ||
            steps.lint_css.outcome == 'failure' ||
            steps.unit_tests.outcome == 'failure')
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
      - name: Upload loki debug data
        if: failure() && steps.screenshot_tests.conclusion == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: Loki screenshots
          path: |
            storybook-static
            .loki/current
            .loki/difference
            .loki/reference
